In [0]:
import numpy as np

In [2]:
# questao 1
A = np.random.randint(0, 9,(3, 4))
print(A)

[[4 0 3 4]
 [0 1 0 5]
 [4 5 6 4]]


In [3]:
# questao 2
B = np.random.randint(0, 9, (3, 4))
print(B)

[[3 5 4 2]
 [5 6 5 6]
 [8 5 4 2]]


In [4]:
# questao 3
np.clip(A, 1, 4)

array([[4, 1, 3, 4],
       [1, 1, 1, 4],
       [4, 4, 4, 4]])

In [5]:
np.clip(B, 1, 4)

array([[3, 4, 4, 2],
       [4, 4, 4, 4],
       [4, 4, 4, 2]])

In [6]:
# questao 4
print(A.dtype)
print(B.dtype)

print(A.shape)
print(B.shape)


int64
int64
(3, 4)
(3, 4)


In [7]:
# questao 5
C = np.full((3,4), 2) 
C

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [8]:
# questao 6
D = A + 2*B
D

array([[10, 10, 11,  8],
       [10, 13, 10, 17],
       [20, 15, 14,  8]])

In [9]:
# questao 7
E = np.array(np.mat('1;2;3;4'))
E

array([[1],
       [2],
       [3],
       [4]])

In [10]:
# questao 8
F = np.dot(B,E)
F

array([[33],
       [56],
       [38]])

In [11]:
# questao 9
G = np.copy(F)
G

array([[33],
       [56],
       [38]])

In [12]:
# questao 10
np.sum(A)

36

In [13]:
# questao 11
A = A.astype(float)
A.dtype

dtype('float64')

In [14]:
# questao 12
A = np.resize(A,(4,3))
A

array([[4., 0., 3.],
       [4., 0., 1.],
       [0., 5., 4.],
       [5., 6., 4.]])

In [15]:
# questao 13
np.concatenate((A[0], A[1], A[2]))

array([4., 0., 3., 4., 0., 1., 0., 5., 4.])

In [16]:
# questao 14
newrow = [1.,2.,3.]
A = np.vstack([A, newrow])
A

array([[4., 0., 3.],
       [4., 0., 1.],
       [0., 5., 4.],
       [5., 6., 4.],
       [1., 2., 3.]])

In [17]:
# questao 15
np.linspace(0,1,5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])